Mini_project/Mini_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lecture/", include("lecture.urls")),
    path("user/", include("user.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Mini_project/lecture/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.lecture_list, name="lecture-list"),
    path(
        "category/<int:category_id>",
        views.lecture_list_in_category,
        name="lecture-list-in-category",
    ),
    path(
        "category/<int:category_id>/detail/<int:lecture_id>",
        views.lecture_detail,
        name="lecture-detail",
    ),
    path(
        "search/<str:search_word>",
        views.lecture_search,
        name="lecture-search",
    ),
]

Mini_project/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "user"

urlpatterns = [
    path(
        "login",
        auth_views.LoginView.as_view(template_name="user/login.html"),
        name="login",
    ),
    path(
        "logout",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path("register", views.register, name="register"),
]

Mini_project/lecture/models.py
from django.db import models
from django.utils import timezone
from django.core import validators
from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.
class Sites(models.Model):
    site_name = models.CharField(max_length=50)
    site_url = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Categories(models.Model):
    cat_name = models.CharField(max_length=200)
    cat_parent = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Lecturers(models.Model):
    lecturer_name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Lectures(models.Model):
    site = models.ForeignKey(Sites, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Categories,
                                 on_delete=models.SET_NULL,
                                 null=True)
    lecturer = models.ForeignKey(Lecturers,
                                 on_delete=models.SET_NULL,
                                 null=True)
    lec_title = models.CharField(max_length=200)
    lec_img_link = models.CharField(max_length=500)
    lec_link = models.CharField(max_length=500)
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    review_count = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comments(models.Model):
    lecture = models.ForeignKey(Lectures, on_delete=models.SET_NULL, null=True)
    content = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Mini_project/lecture/forms.py
from django import forms
from .models import Comments


class BootstrapModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._widget_update()

    def _widget_update(self):
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


class CommentForm(BootstrapModelForm):

    class Meta:
        model = Comments
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={"placeholder": "리뷰를 작성하세요."}),
        }

Mini_project/lecture/views.py
from django.shortcuts import render, get_object_or_404, redirect
from lecture.models import Categories, Lectures, Comments
from django.core.paginator import Paginator
from django.http import Http404
from .forms import CommentForm


# Create your views here.
def lecture_list(request):
    # page = int(request.GET.get("page", 1))
    # PAGE_SIZE = 20

    # start, end = (page - 1) * PAGE_SIZE, page * PAGE_SIZE

    # category_list = Categories.objects.all()
    # lecture_list = Lectures.objects.prefetch_related(
    #     "comments_set").all()[start:end]

    # page_numbers = list(range(start + 1, end + 2))
    category_list = Categories.objects.all()
    # lecture_list = Lectures.objects.filter(
    #     category_id=category_list[0].id).order_by("-created_at")
    lecture_list = Lectures.objects.all().order_by("-created_at")

    PAGE_SIZE = 20
    paginator = Paginator(lecture_list, PAGE_SIZE)

    page_number = request.GET.get("page")
    lecture_page_obj = paginator.get_page(page_number)

    response = render(
        request,
        "lecture/lecture-list.html",
        {
            "category_list": category_list,
            "lecture_list": lecture_page_obj,
        },
    )
    return response


def lecture_list_in_category(request, category_id):
    category_list = Categories.objects.all()
    lecture_list = Lectures.objects.filter(
        category_id=category_id).order_by("-created_at")

    PAGE_SIZE = 20
    paginator = Paginator(lecture_list, PAGE_SIZE)

    page_number = request.GET.get("page")
    lecture_page_obj = paginator.get_page(page_number)

    response = render(
        request,
        "lecture/lecture-list.html",
        {
            "category_list": category_list,
            "lecture_list": lecture_page_obj,
        },
    )
    return response


def lecture_detail(request, category_id, lecture_id):
    category_list = Categories.objects.all()

    # try:
    #     lecture = Lectures.objects.filter(
    #         id=lecture_id).prefetch_related("comments_set")
    # except Lectures.DoesNotExist:
    #     raise Http404
    # lecture = get_object_or_404(Lectures, id=lecture_id)
    # lecture_info = Lectures.objects.filter(id=lecture_id)
    lecture = Lectures.objects.filter(category_id=category_id).get(
        id=lecture_id)
    comment_list = lecture.comments_set.all()
    form = CommentForm()

    if request.method == "POST":
        form = CommentForm(request.POST)

        if form.is_valid():
            data = form.data
            comment = Comments(
                content=data["content"],
                lecture_id=lecture_id,
                user_id=request.user.id,
            )
            comment.save()
            return redirect(
                f"/lecture/category/{category_id}/detail/{lecture_id}")

    response = render(
        request,
        "lecture/lecture-detail.html",
        {
            "category_list": category_list,
            "lecture_info": lecture,
            "comment_list": comment_list,
            "form": form,
        },
    )
    return response


def lecture_search(request, search_word):
    category_list = Categories.objects.all()

    lecture_list = Lectures.objects.filter(
        lec_title__icontains=search_word).order_by("-created_at")

    PAGE_SIZE = 20
    paginator = Paginator(lecture_list, PAGE_SIZE)

    page_number = request.GET.get("page")
    lecture_page_obj = paginator.get_page(page_number)

    response = render(
        request,
        "lecture/lecture-list.html",
        {
            "category_list": category_list,
            "lecture_list": lecture_page_obj,
            "search_word": search_word,
        },
    )
    return response

Mini_project/lecture/templates/lecture/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduDevReview</title>
    <link rel="stylesheet" href="{% static 'lecture/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block styles %}{% endblock %}
  </head>

  <body>

    {% block layout %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
  </body>

</html>

Mini_project/lecture/templates/lecture/footer.html
<!-- FOOTER -->
<footer class="container">
  {% comment %} <p class="float-end">
    <a href="#">Back to top</a>
  </p>
  <p>&copy; 2017–2024 Company, Inc. &middot;
    <a href="#">Privacy</a>
    &middot;
    <a href="#">Terms</a>
  </p> {% endcomment %}
</footer>

Mini_project/lecture/templates/lecture/header.html
{% load static %}
<header class="header">
  <nav class="navbar">
    <a href="/lecture" class="logo"><img class="logo_img" src="{% static 'images/logo.jpg' %}" alt=""></a>
    <div class="nav-links">
      {% for category in category_list %}
        <a href="{% url 'lecture-list-in-category' category.id %}">{{ category.cat_name }}</a>
      {% endfor %}
    </div>
    <div class="search-container">
      <input type="search" class="form-control search-input" placeholder="검색" aria-label="Search" name="search_word" value="{{ search_word }}">
      <button class="search-btn" type="submit">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
        </svg>
      </button>
    </div>
    
    <div class="auth-buttons">
      {% if user.is_authenticated %}
        <div class="user-menu-container">
          <div class="user-logo" id="userLogo" style="background-image: url('{% static 'images/logo.jpg' %}');"></div>
          <div class="user-dropdown" id="userDropdown">
            <div class="user-info">
              <img src="{% static 'images/apple.jpg' %}" alt="User Profile">
              <div class="user-details">
                <h6>{{ user.username }}</h6>
                <p>사용자</p>
              </div>
            </div>
            <div class="menu-item">
              <i class="fas fa-book"></i>
              <span>내가 들은 학습</span>
            </div>
            <div class="menu-item">
              <i class="fas fa-play-circle"></i>
              <span>내가 단 리뷰보기</span>
            </div>
            <div class="menu-item">
              <i class="fas fa-tachometer-alt"></i>
              <span>대시보드</span>
            </div>
            <div class="menu-item">
              <i class="fas fa-shopping-cart"></i>
              <span>구매 내역</span>
            </div>
            <div class="menu-item">
              <i class="fas fa-heart"></i>
              <span>좋아요</span>
            </div>
            <div class="menu-item">
              <i class="fas fa-cog"></i>
              <span>설정</span>
            </div>
            <div class="logout">
              <form method="POST" action="{% url 'user:logout' %}">
                {% csrf_token %}
              <button class="btnlogin-popup" type="submit">로그아웃</button>
              </form>
            </div>
          </div>
        </div>
      {% else %}
        {% comment %} <button class="btnlogin-popup" type="summit">로그인</button>
        <button class="btnsignup-popup" type="summit">회원가입</button> {% endcomment %}
        <a class="btnlogin-popup" href="{% url 'user:login' %}">로그인</a>
        <a class="btnsignup-popup" href="{% url 'user:register' %}">회원가입</a>
      {% endif %}
    </div>
  </nav>
</header>

Mini_project/lecture/templates/lecture/layout.html
{% extends "lecture/base.html" %}
{% block layout %}
  {% include "./header.html" %}

  <main>
    {% block contents %}{% endblock %}

    <div>
      {% include "./footer.html" %}
    </div>
  </main>
{% endblock %}

Mini_project/lecture/templates/lecture/lecture-detail.html
{% comment %} {% extends "./layout.html" %} {% endcomment %}
{% load static %}
{% block styles %}
  <link rel="stylesheet" href="{% static 'lecture/review.css' %}" type="text/css">
{% endblock %}
{% block contents %}
  <div class="course-detail">
    <div class="course-card">
        <div class="course-image">
           <img src="{{ lecture_info.lec_img_link }}" alt="{{ lecture_info.lec_title }}">
        </div>
        <div class="course-info">
        <h1 id="course-title">{{ lecture_info.lec_title }}</h1>
        <p id="course-instructor">강사: {{ lecture_info.lecturer.lecturer_name }}</p>
        <p id="course-rating">평점: ★ {{ lecture_info.rating }}</p>
        </div>
    </div>
  </div>

  <div class="comments-section">
    <h2>리뷰 및 댓글</h2>
    <div id="comments-list">
        <ul>
            {% for comment in comment_list %}
            <li>{{ comment.content }}</li>
            {% endfor %}
        </ul>
    </div>
    {% if user.is_authenticated %}
    <div class="comment-form">
      <form method="POST">
        {% csrf_token %}
        내용:
        {{ form.content }}
      {% comment %} <textarea id="comment-input" placeholder="리뷰를 작성하세요..."></textarea> {% endcomment %}
        <button id="submit-comment">댓글 작성</button>
      </form>
    </div>
    {% endif %}
  </div>
{% endblock %}
{% block scripts %}
  <script src="{% static 'js/review.js' %}"></script>
{% endblock %}

Mini_project/lecture/templates/lecture/lecture-list.html
{% extends "./layout.html" %}
{% load humanize %}
{% load static %}

{% block contents %}
  <section class="course-section">
    <h2 class="section-title">강의 목록</h2>
    <div class="course-container">
      {% for lec in lecture_list %}
        <div class="course-card" data-id="{{ lec.id }}" data-category="">
          <img src="{{ lec.lec_img_link }}" alt="{{ lec.lec_title }}" class="course-image">
          <div class="course-info">
            {% comment %} <a href="{{ lec.lec_link }}" class="course-title">{{ lec.lec_title }}</a> {% endcomment %}
            <a href="{% url 'lecture-detail' lec.category_id lec.id %}" class="course-title">{{ lec.lec_title }}</a>
            <div class="course-instructor">{{ lec.lecturer.lecturer_name }}</div>
            <div class="course-rating">
              <span class="star">★</span>
              <span class="rating-number">{{ lec.rating }}</span>
              <span class="review-count">({{ lec.review_count|intcomma }})</span>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    <div class="d-flex justify-content-center my-4">
      <nav aria-label="Page navigation">
          <ul class="pagination">
              {% if lecture_list.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page=1" aria-label="First">
                          <span aria-hidden="true">&laquo;&laquo;</span>
                      </a>
                  </li>
                  <li class="page-item">
                      <a class="page-link" href="?page={{ lecture_list.previous_page_number }}" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                      </a>
                  </li>
              {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" aria-label="First">
                          <span aria-hidden="true">&laquo;&laquo;</span>
                      </a>
                  </li>
                  <li class="page-item disabled">
                      <a class="page-link" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                      </a>
                  </li>
              {% endif %}
  
              {% for num in lecture_list.paginator.page_range %}
                  {% if lecture_list.number == num %}
                      <li class="page-item active">
                          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                      </li>
                  {% elif num > lecture_list.number|add:'-3' and num < lecture_list.number|add:'3' %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                      </li>
                  {% endif %}
              {% endfor %}
  
              {% if lecture_list.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ lecture_list.next_page_number }}" aria-label="Next">
                          <span aria-hidden="true">&raquo;</span>
                      </a>
                  </li>
                  <li class="page-item">
                      <a class="page-link" href="?page={{ lecture_list.paginator.num_pages }}" aria-label="Last">
                          <span aria-hidden="true">&raquo;&raquo;</span>
                      </a>
                  </li>
              {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" aria-label="Next">
                          <span aria-hidden="true">&raquo;</span>
                      </a>
                  </li>
                  <li class="page-item disabled">
                      <a class="page-link" aria-label="Last">
                          <span aria-hidden="true">&raquo;&raquo;</span>
                      </a>
                  </li>
              {% endif %}
          </ul>
      </nav>
  </div>
  
  </section>
  

  <div id="loginModal" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span>
      <div class="login-form">
        <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo-img">
        <form method="POST" action="{% url 'user:login' %}">
          {% csrf_token %}
          <input type="email" placeholder="이메일" required="required">
          <input type="password" placeholder="비밀번호" required="required">
          <button type="submit" class="login-btn">로그인</button>
          <div class="links">
            <a href="#">비밀번호 찾기</a>
            |
            <a href="{% url 'user:register' %}">회원가입</a>
            |
            <a href="#">아이디(이메일) 찾기</a>
          </div>
          <div class="social-login">
            <p>간편 로그인</p>
            <div class="social-icons">
              <a href="#"><img src="{% static 'images/kakao.png' %}" alt="Kakao"></a>
              <a href="#"><img src="{% static 'images/google.png' %}" alt="Google"></a>
              <a href="#"><img src="{% static 'images/github.png' %}" alt="GitHub"></a>
              <a href="#"><img src="{% static 'images/apple.png' %}" alt="Apple"></a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script src="{% static 'js/script.js' %}"></script>
{% endblock %}